"""create passenger profile

Revision ID: 6d2dae6bf070
Revises: 2f803ae1215a
Create Date: 2026-08-29 09:44:56.384031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2dae6bf070'
down_revision: Union[str, Sequence[str], None] = '2f803ae1215a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passenger_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_language', sa.String(length=20), nullable=False),
    sa.Column('home_location', sa.String(length=255), nullable=True),
    sa.Column('work_location', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passenger_profiles_user_id'), 'passenger_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passenger_profiles_user_id'), table_name='passenger_profiles')
    op.drop_table('passenger_profiles')
    # ### end Alembic commands ###
